# Cloudflare tunnel override - removes Traefik for direct tunnel connection
# Use this file when deploying with Cloudflare tunnels for maximum security and simplicity
# 
# Usage:
#   docker compose -f docker-compose.yml -f docker-compose.cloudflare.yml up -d
#
# Architecture:
#   Internet → Cloudflare → cloudflared → n8n services (direct)
#   No reverse proxy, no open ports, maximum security

# No additional volumes needed - traefik_data volume will be ignored

services:
  # Configure n8n services to work directly with cloudflared
  n8n:
    labels: {}  # Remove all Traefik labels
    ports:
      # Only expose ports locally for debugging if needed
      # Cloudflare tunnel connects directly to container port 5678
      - "127.0.0.1:5678:5678"  # n8n UI (localhost only)

  n8n-webhook:
    labels: {}  # Remove all Traefik labels  
    ports:
      # Webhook service accessible through cloudflared
      - "127.0.0.1:5679:5678"  # n8n webhook (localhost only)

  # Cloudflared service for direct tunnel connection
  cloudflared:
    image: cloudflare/cloudflared:latest
    platform: linux/amd64
    depends_on:
      - n8n
      - n8n-webhook
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    # Use simple tunnel token mode instead of config file for easier setup
    # Ingress rules are configured in Cloudflare dashboard instead of config file
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}